# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 2, 14, 1, 35, 447049, tzinfo=utc)),
        ),
    ]
